name = "bybit-api-relay"
main = "worker.js"
compatibility_date = "2024-01-01"

# Secrets (set via: wrangler secret put SECRET_NAME)
# - BYBIT_API_KEY: Your Bybit API key
# - BYBIT_API_SECRET: Your Bybit API secret  
# - RELAY_AUTH_TOKEN: Random token to authenticate Replit backend

[env.production]
name = "bybit-api-relay"
